### ISSUE TITLE
Calls to super.[lifecycle] shouldn't be rewritten as unsafe for rename-unsafe-lifecycles

### ISSUE THREAD

**Issue by James-E-Adams** [reactjs/react-codemod#242]
This seems like a bug but not sure if this is within scope of the codemod's intended 'smartness'. 

I have a class component that extends from a component imported from a library.

In this class component, it implements `componentWillReceiveProps`. It also makes a call to `super.componentWillReceiveProps()`. The code mod changed it from:

```js
componentwillReceiveProps(nextProps) {
     super.componentWillReceiveProps(nextProps)
     ....
} 
```

to 

```js
UNSAFE_componentwillReceiveProps(nextProps) {
     super.UNSAFE_componentWillReceiveProps(nextProps)
     ....
} 
```
But this relies on the vendor code having changed its implementation to be named UNSAFE too. 

I think in this instance, the method for the component in my own codebase should be modified to UNSAFE but the call to super shouldn't be modified to call the UNSAFE equivalent.

**Comment by threepointone** [comment]
So it's an awkward pattern, and not idiomatic, for people to extend from React.Component for their own components. That said, the reason this codemod does this in the first place, is *because* we discovered usages where it was done so (https://github.com/reactjs/react-codemod/pull/198). The correct fix here, would be to  apply the codemod on the dependencies too (or make the proper substitutions). It would be hard for the codemod to decide what a vendor/third-party dependency is (and worse, to let it be as is, because it would break in the future). 

I'm sorry this caused you trouble, but I hope you understand that we'd rather err on correctness; with the codemod you'd see your code fail immediately (or you'd discover it when you see your diff).

I'm closing this issue, but happy to revisit if it turns out to be a wider problem.

**Comment by James-E-Adams** [comment]
Hi Sunil! 
Yeah it's a tricky situation. 
I'm not certain applying the codemod on the third-party dependency would be the greatest idea. It's _usually_ outside of source control and you're right - it's hard to determine what exactly is third-party. But this is totally outside of the scope for a simple codemod.
Thanks for taking the time to respond!
