### ISSUE TITLE
Maybe it's a RFC

### ISSUE THREAD

**Issue by behnammodi** [reactjs/react-codemod#274]
How to change, remove or add a props to component by `react-codemod` for exapmle:

I have a component like this:

```jsx
function Header(){
    return <div id="header"></div>
}
```
Now, I want to remove `id` props from all component so result is:

```jsx
function Header(){
    return <div></div>
}
```

I think it can be possible like this command

```bash
npx react-codemod remove-props 'id'
```

**Comment by gaearon** [comment]
You’d need to write your own codemod. Please search the internet for “how to write a codemod with jscodeshift”.

**Comment by behnammodi** [comment]
@gaearon Why you are angry?

**Comment by gaearon** [comment]
Sorry, I didn't mean to sound angry!

I'm saying that in order to implement the functionality you want, you need to write your own codemod. This is because `react-codemod` is not an extensible codemod engine — it's a collection of preexisting codemods. If you want to write your own, you need to use `jscodeshift`. I'm suggesting that you search for a jscodeshift tutorial because it should be helpful to achieve your goals.

Does this make sense?

**Comment by behnammodi** [comment]
@gaearon Thanks man, it's great
