### ISSUE TITLE
The script skips files that have mixins in them

### ISSUE THREAD

**Issue by fullvlad** [reactjs/react-codemod#6]
When running this command:
`jscodeshift -t ~/react-codemod/transforms/class.js filename.jsx`

For the files that have mixins in them I get:
`filename.jsx: 'Component' was skipped because of mixins.`

although the component is defined with `React.createClass()` and the script should create ES2015 classes.

How should I still use the script and work around mixins?

**Comment by hzoo** [comment]
Mixins currently aren't able to be supported with ES6 classes so you would have to either not use ES6 clasess or remove the mixins and then run the script? Then replace the mixins (could use decorators, higher order components) https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.l7soi93mm

**Comment by cpojer** [comment]
We do not have the static analysis tools available to be able to safely transform any kind of mixin. As @hzoo said, you have to remove all your mixins first. If you have many files with the same mixins, you can write a script that updates these files and removes the mixins. Otherwise I'd recommend just doing it manually.
